import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'

import type { ConfigMutant } from './explorer/surfaces.ts'
import { MOCK_API_KEY } from './mock/server.ts'
import type { LaunchProfile } from './types.ts'

export type Sandbox = {
  root: string
  hermesHome: string
  userDataDir: string
}

export function createSandbox(prefix: string): Sandbox {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), `hermes-fuzz-${prefix}-`))
  const hermesHome = path.join(root, 'hermes-home')
  const userDataDir = path.join(root, 'electron-user-data')
  fs.mkdirSync(hermesHome, { recursive: true })
  fs.mkdirSync(path.join(hermesHome, 'logs'), { recursive: true })
  fs.mkdirSync(userDataDir, { recursive: true })
  fs.writeFileSync(
    path.join(userDataDir, 'window-state.json'),
    JSON.stringify({ x: 40, y: 40, width: 1280, height: 800, isMaximized: false }, null, 2),
    'utf8',
  )
  fs.writeFileSync(path.join(userDataDir, 'zoom-state.json'), JSON.stringify({ zoomLevel: 0 }), 'utf8')
  return { root, hermesHome, userDataDir }
}

export function writeMockConfig(hermesHome: string, mockUrl: string, mutant: ConfigMutant = 'sane'): void {
  let config = ''
  if (mutant === 'broken-yaml') {
    config = 'model: {\n  this is not: [valid yaml\n'
  } else if (mutant === 'missing-provider') {
    config = '# fuzzer no-provider / missing-provider mutant\n'
  } else if (mutant === 'huge-context') {
    config = `# Generated by hermes-agent-fuzzer. Isolated sandbox only.
model:
  default: mock-model
  provider: mock
providers:
  mock:
    api: ${mockUrl}/v1
    name: Mock
    api_mode: chat_completions
    key_env: MOCK_API_KEY
    models:
      mock-model: {}
    context_length: 100000000
auxiliary:
  title_generation:
    enabled: false
approvals:
  mode: "manual"
`
  } else if (mutant === 'bad-url') {
    config = `# Generated by hermes-agent-fuzzer. Isolated sandbox only.
model:
  default: mock-model
  provider: mock
providers:
  mock:
    api: http://127.0.0.1:1/v1
    name: Mock
    api_mode: chat_completions
    key_env: MOCK_API_KEY
    models:
      mock-model: {}
    context_length: 4096
`
  } else if (mutant === 'auto-approvals') {
    config = `# Generated by hermes-agent-fuzzer. Isolated sandbox only.
model:
  default: mock-model
  provider: mock
providers:
  mock:
    api: ${mockUrl}/v1
    name: Mock
    api_mode: chat_completions
    key_env: MOCK_API_KEY
    models:
      mock-model: {}
    context_length: 4096
approvals:
  mode: "off"
`
  } else {
    config = `# Generated by hermes-agent-fuzzer. Isolated sandbox only.
model:
  default: mock-model
  provider: mock
providers:
  mock:
    api: ${mockUrl}/v1
    name: Mock
    api_mode: chat_completions
    key_env: MOCK_API_KEY
    models:
      mock-model: {}
    context_length: 4096
auxiliary:
  title_generation:
    enabled: false
approvals:
  mode: "manual"
`
  }
  fs.writeFileSync(path.join(hermesHome, 'config.yaml'), config, 'utf8')
  fs.writeFileSync(path.join(hermesHome, '.env'), `MOCK_API_KEY=${MOCK_API_KEY}\n`, 'utf8')
}

export function writeEmptyConfig(hermesHome: string): void {
  fs.writeFileSync(path.join(hermesHome, 'config.yaml'), '# fuzzer no-provider profile\n', 'utf8')
}

export function prepareProfileConfig(
  sandbox: Sandbox,
  profile: LaunchProfile,
  mockUrl: string | null,
  mutant?: ConfigMutant,
): void {
  const chosen = mutant ?? (profile === 'no-provider' ? 'missing-provider' : 'sane')
  if (profile === 'no-provider' || chosen === 'missing-provider') {
    writeEmptyConfig(sandbox.hermesHome)
    return
  }
  writeMockConfig(sandbox.hermesHome, mockUrl ?? 'http://127.0.0.1:9', chosen)
}

export function removeSandbox(sandbox: Sandbox): void {
  try {
    fs.rmSync(sandbox.root, { recursive: true, force: true })
  } catch {
    // Best effort. A locked Electron file can linger on Windows.
  }
}

export function sandboxLooksIsolated(hermesHome: string, userDataDir: string): boolean {
  const home = path.resolve(hermesHome).toLowerCase()
  const userData = path.resolve(userDataDir).toLowerCase()
  const local = (process.env.LOCALAPPDATA ?? '').toLowerCase()
  const appdata = (process.env.APPDATA ?? '').toLowerCase()
  if (local && home.startsWith(path.join(local, 'hermes').toLowerCase())) {
    return false
  }
  if (appdata && userData.startsWith(path.join(appdata, 'hermes').toLowerCase())) {
    return false
  }
  return fs.existsSync(hermesHome) && fs.existsSync(userDataDir)
}
